#!/usr/bin/python

### /home/falles/bin/python2.7

from time import sleep
import os.path
import socket
import subprocess
import sys

def updatepidfile(IAEE_HOME, pid):
   try:
      pidfile = open(IAEE_HOME + '/.client/client-' + str(socket.gethostname()) + '.pid', 'w')
   except IOError:
      updated = False
   else:
      pidfile.write(str(pid) + '\n')
      pidfile.close()
      updated = True
   return updated

def startclient(IAEE_HOME, quiet):
   if quiet:
      iaee = subprocess.Popen(['java', '-jar', IAEE_HOME + '/jar/iaee.jar', '-c'], stdout=open(IAEE_HOME + '/.client/client-' + str(socket.gethostname()) + '-stdout.tty', 'a'), stderr=open(IAEE_HOME + '/.client/client-' + str(socket.gethostname()) + '-stderr.tty', 'a')) 
      # update IAEE_HOME/.master/master-$HOSTNAME.pid
      updatepidfile(IAEE_HOME, iaee.pid)
   else:
      iaee = subprocess.Popen(['java', '-jar', IAEE_HOME + '/jar/iaee.jar', '-c']) 
      # update IAEE_HOME/.master/master-$HOSTNAME.pid
      while not updatepidfile(IAEE_HOME, iaee.pid):
         pass
      try:
         iaee.wait()
      except KeyboardInterrupt:
         print
         print('iaee-client killed.')
   return True

def helpmsg(IAEE_HOME):
   print("iaee-client: starts a client iaee instance.")
   print
   print("Usage:")
   print("     <iaee-client> runs verbosely, printing everything to the current terminal.")
   print("     <iaee-client verbose> runs verbosely, printing everything to the current terminal.")
   print("     <iaee-client quiet> quiet run - output is redirected to " + IAEE_HOME + "/.client/client-" + str(socket.gethostname()) + "-stdout.tty and " + IAEE_HOME + "/.client/client-" + str(socket.gethostname()) + "-stderr.tty.")
   print("     <iaee-client help> prints this help message.")
   return True

def gethelpmsg():
   print("Wrong usage.")
   print("Type <iaee-client> for usage instructions.")
   return True

def main(argv):
   IAEE_HOME = os.path.expanduser('~') + '/.iaee' 
   if len(argv) == 0:
      print("Starting iaee client instance...")
      sleep(1)
      status = subprocess.call([os.path.expanduser('~') + '/bin/iaee-status', 'quiet'])
      if status == 2 or status == 3:
         print("iaee-client already running on " + str(socket.gethostname()) + ".")
         sleep(1)
      else:
         startclient(IAEE_HOME, False)
   elif len(argv) == 1:
      if argv[0] == 'verbose':
         print("Starting iaee client instance...")
         sleep(1)
         status = subprocess.call([os.path.expanduser('~') + '/bin/iaee-status', 'quiet'])
         if status == 2 or status == 3:
            print("iaee-client already running on " + str(socket.gethostname()) + ".")
            sleep(1)
         else:
            startclient(IAEE_HOME, False)
      elif argv[0] == 'quiet':
         print("Starting iaee client instance...")
         sleep(1)
         status = subprocess.call([os.path.expanduser('~') + '/bin/iaee-status', 'quiet'])
         if status == 2 or status == 3:
            print("iaee-client already running on " + str(socket.gethostname()) + ".")
            sleep(1)
         else:
            startclient(IAEE_HOME, True)
      elif argv[0] == 'help':
         helpmsg(IAEE_HOME)
      else:
         gethelpmsg()
   else:
      gethelpmsg()

if __name__ == "__main__":
   main(sys.argv[1:])
