#!/bin/bash

if [ $# -eq 1 ]
then
  index=0
  ps aux | grep iaee.jar
  echo "---------------------------------------------------"
  pids=`ps aux | grep iaee.jar | tr -s ' ' | cut -d ' ' -f 2`  
  while [ $index -ne $1 ]; do 
    index=$(($index+1))
    pid=`echo $pids | cut -d ' ' -f $index`  
    kill -9 $pid
  done
  sleep 3
  ps aux | grep iaee.jar
else
  echo "Wrong usage."
  echo "killiaee <# of iaee instances to be killed>"
fi
